# Generated by Django 3.1.2 on 2020-12-16 22:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0006_auto_20201216_1148'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='archived',
        ),
    ]
