# Generated by Django 3.1.2 on 2020-12-17 16:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0008_follower_leaders'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Leaders',
            new_name='Leader',
        ),
        migrations.RenameField(
            model_name='follower',
            old_name='username',
            new_name='followerName',
        ),
        migrations.RenameField(
            model_name='leader',
            old_name='username',
            new_name='leaderName',
        ),
        migrations.AlterField(
            model_name='leader',
            name='followers',
            field=models.ManyToManyField(related_name='following', to=settings.AUTH_USER_MODEL),
        ),
    ]
