# Generated by Django 3.1.2 on 2020-12-17 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0009_auto_20201217_1112'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leader',
            name='followers',
        ),
        migrations.RemoveField(
            model_name='leader',
            name='leaderName',
        ),
        migrations.DeleteModel(
            name='Follower',
        ),
        migrations.DeleteModel(
            name='Leader',
        ),
    ]
