# Generated by Django 3.1.2 on 2020-12-22 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0011_auto_20201221_1039'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='preference',
            field=models.CharField(choices=[('Like', 'Like'), ('Dislike', 'Dislike')], default='Like', max_length=7, null=True),
        ),
    ]
