# Generated by Django 3.1.2 on 2020-12-22 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0015_auto_20201222_1158'),
    ]

    operations = [
        migrations.RenameField(
            model_name='liking',
            old_name='username',
            new_name='bywhom',
        ),
    ]
