# Generated by Django 3.1.2 on 2020-12-22 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0016_auto_20201222_1231'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='liking',
            name='preference',
        ),
        migrations.AddField(
            model_name='liking',
            name='like',
            field=models.BooleanField(default=True),
        ),
    ]
