# Generated by Django 3.1.2 on 2020-12-23 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0018_auto_20201223_0953'),
    ]

    operations = [
        migrations.AlterField(
            model_name='liking',
            name='preference',
            field=models.CharField(choices=[('Like', 'Like'), ('Unlike', 'Unlike')], default='Like', max_length=7, null=True),
        ),
    ]
